DROP DATABASE IF EXISTS chat_app;
CREATE DATABASE chat_app;
USE chat_app;

CREATE TABLE messages(
id INT PRIMARY KEY AUTO_INCREMENT,
message VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);